### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by squalrus** [RitsC/PrintArea#1]
Would really like to use this plugin, but would require the licence to be updated -- preferably MIT. Thanks.

**Comment by RitsC** [comment]
Can you please elaborate on this necessity?

**Comment by squalrus** [comment]
Would like to use the plugin in a Commercial setting, but we have requirements from our customers that limit us to include software that has certain licenses. MIT is what we are most compatible with. Hope that helps!

**Comment by RitsC** [comment]
now licensed under MIT
