### ISSUE TITLE
Ie10 modal prints entire body content?

### ISSUE THREAD

**Issue by pre2612** [RitsC/PrintArea#21]
Trying to do print of a modal get entire body printed in ie10 & ie 11?

**Comment by RitsC** [comment]
cannot reproduce using demo.

**Comment by pre2612** [comment]
I have tried working on it it's a bootstrap modal I see entire page content.
If I add:
display:none; to main content then Ie doesnt display anything on print all other browsers work fine

can you please help me with this

**Comment by RitsC** [comment]
If you can setup a demo, I may be able to take a look.

**Comment by pre2612** [comment]
I worked i have changed css. Thanks
