### ISSUE TITLE
Printing not working in CHROME.

### ISSUE THREAD

**Issue by amrutraj** [RitsC/PrintArea#25]
Blank page is shown in print preview for google Chrome. Thus nothing is printed.

STEP TO REPRODUCE PROBLEM - 
0. Go to this page in google CHROME, http://www.jqueryscript.net/demo/Print-Specified-Area-Of-A-Page-PrintArea/demo/
1. call .printArea with popup mode.  it will show a chrome print preview.
2. That preview has nothing in it. So close it.
3. NOW you will see the popup of text to be printed. Press ctrl + p to print that text. Prints successfully.

**Comment by RitsC** [comment]
This is a duplicate of issue #15, see the comments from @KEggleston. Get the latest version.
