### ISSUE TITLE
extra css + copy also css with media="all"

### ISSUE THREAD

**Issue by DiegoSSJ** [RitsC/PrintArea#3]
Hi!

I have started using this plugin and made a slight enhancement plus made it so that all css on the original page with media="all" were copied as well to the iframe or popup to print.

Here are my code changes:
-  @popClose | [boolean] | (false),true           | popup window close after printing
-  <LiU>
-  @extraCss | [string]  | (''), "http://www.liu.se/mall11/css/print-news.css,http://www.liu.se/mall11/css/another-css.css" | Komma separated list of extra css files to load in the <head> section of the popup or iframe
-  </LiU>
  
  ```
               popClose : false,
       extraCss : '' };
  ```
  
  var settings = {};//global settings
  
  ```
              return (media == undefined || media.toLowerCase() == "" || media.toLowerCase() == "print" || media.toLowerCase() == "all" )
  ```
  
  if ( settings.extraCss ){
      for(i = 0; i < settings.extraCss.split(",").length; i++){
          head+= '<link type="text/css" rel="stylesheet" href="' + settings.extraCss.split(",")[i] + '" >';
      }
  }

**Comment by DerDu** [comment]
Please include media="all" :+1:

**Comment by RitsC** [comment]
Hey guys, sorry it has taken me so long to include these enhancements. Been busy.
Let me know if you have any problems with these changes.

**Comment by DiegoSSJ** [comment]
Thanks! No problem at  all

Sorry for wrongly including the source code, I think I forgot to preview the tags.
