### ISSUE TITLE
Print no colors

### ISSUE THREAD

**Issue by manzanofab** [RitsC/PrintArea#7]
Hi 
First of all, amazing work.
I am just having an issue that my page doesnt send the colors like on the demo where XYZ are red 
I am using the latest jquery from cdn (//cdnjs.cloudflare.com/ajax/libs/jquery/2.0.3/jquery.min.js)
and the jquery.PrintArea.js
I am not using an external css file for the page where I want to print, could this be th eproblem?
Thanks

**Comment by RitsC** [comment]
Thank you.  

When you say "external css file", what do you mean by that?  The plugin will select the &lt;link&gt; elements, located  between the &lt;head&gt; tags on the web page, then filter out some elements based on the media type and copy them to the target print document. 

Hope that helps.
